# Generated by Django 4.0.3 on 2022-04-13 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empregados', '0003_alter_empregados_user'),
        ('documentos', '0002_documentos_pertence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='pertence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='empregados.empregados'),
            preserve_default=False,
        ),
    ]
