# Generated by Django 4.0.3 on 2022-04-13 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empregados', '0002_empregados_departamento_empregados_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empregados',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
