# Generated by Django 4.0.3 on 2022-04-13 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empregados', '0002_empregados_departamento_empregados_empresa_and_more'),
        ('registro_de_horas_extras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohoras',
            name='empregados',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='empregados.empregados'),
            preserve_default=False,
        ),
    ]
